spring.application.name=drwise-todo-springboot

server.port=8080

# allow devtools restart suport
spring.devtools.restart.enabled=true

springdoc.swagger-ui.path=/api/v1/docs.html

spring.profiles.active=dev