# setup local postgresql database config
spring.datasource.url=jdbc:postgresql://localhost:5434/drwise_todo_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=drwise_todo_db_user
spring.datasource.password=db_dev_pass@26
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=Zeg4BVlqPWPKtMn1IMFWXl77bPf2vKHG9aXB5u0eGRk=
jwt.expiration-seconds=3600